<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Première migration du projet : les comptes du dashboard et l'authentification
 * par code e-mail.
 */
final class Version20260909044058 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Comptes du dashboard, codes de connexion et journal des tentatives';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(120) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D3656A4E7927C74 ON account (email)');
        $this->addSql('CREATE TABLE login_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(20) NOT NULL, email VARCHAR(180) DEFAULT NULL, ip VARCHAR(45) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_login_attempt_email ON login_attempt (kind, email, created_at)');
        $this->addSql('CREATE INDEX idx_login_attempt_ip ON login_attempt (kind, ip, created_at)');
        $this->addSql('CREATE TABLE login_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_hash VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, consumed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, tries SMALLINT DEFAULT 0 NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_login_code_account ON login_code (account_id)');
        $this->addSql('ALTER TABLE login_code ADD CONSTRAINT FK_B167BBDD9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE login_code DROP CONSTRAINT FK_B167BBDD9B6B5FBA');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE login_attempt');
        $this->addSql('DROP TABLE login_code');
    }
}
